/** Cobalt Signal Architecture: a signal-spine homepage that opens with decisive technical clarity, not a generic centered marketing stack. */
import { ArrowDownRight, ArrowUpRight, CirclePlay, MoveUpRight } from "lucide-react";
import { Link } from "wouter";
import { products, articles } from "@/data/content";
import { CaseStudyCarousel } from "@/components/CaseStudyCarousel";

function SectionLabel({ index, children }: { index: string; children: string }) { return <p className="signal-kicker flex items-center gap-3"><span className="text-[#6e9aff]">{index}</span><span className="h-px w-8 bg-[#185CFF]" />{children}</p>; }

export default function Home() {
  return <div>
    <section className="relative isolate min-h-[790px] overflow-hidden border-b border-white/10 pt-[74px]"><div className="absolute inset-0 hero-grid opacity-70" aria-hidden="true" /><div className="absolute -right-[14%] top-[13%] h-[620px] w-[620px] rounded-full border border-[#185CFF]/25 blur-[1px]" aria-hidden="true" /><div className="absolute right-[7%] top-[24%] h-[420px] w-[420px] rounded-full border border-white/[0.08]" aria-hidden="true" /><div className="absolute right-[23%] top-[33%] h-[290px] w-[290px] rounded-full border border-[#185CFF]/35 shadow-[0_0_100px_rgba(24,92,255,.18)]" aria-hidden="true" /><div className="absolute right-[28%] top-[38%] h-[190px] w-[190px] bg-[#185CFF]/15 blur-3xl" aria-hidden="true" /><div className="absolute bottom-[17%] right-[9%] h-3 w-3 bg-[#185CFF] shadow-[0_0_24px_6px_rgba(24,92,255,.65)]" aria-hidden="true" /><div className="absolute bottom-[26%] right-[31%] h-2 w-2 bg-slate-200" aria-hidden="true" />
      <div className="relative mx-auto grid min-h-[716px] max-w-[1440px] grid-cols-1 px-5 pb-12 pt-14 lg:grid-cols-[92px_minmax(0,1fr)_330px] lg:px-10 lg:pt-20"><aside className="hidden border-r border-white/10 pr-6 lg:block"><div className="sticky top-28 flex h-[400px] flex-col justify-between"><p className="writing-mode-vertical text-[0.62rem] font-bold uppercase tracking-[0.18em] text-slate-600">PorTech / Decision infrastructure</p><p className="text-[0.62rem] font-bold uppercase tracking-[0.12em] text-[#6e9aff]">01 — 04</p></div></aside><div className="flex flex-col justify-center py-12 lg:px-14"><SectionLabel index="01">Critical systems, made legible</SectionLabel><h1 className="mt-7 max-w-4xl text-[clamp(3.4rem,8vw,7.3rem)] font-semibold leading-[0.88] tracking-[-0.078em] text-white">Make critical<br /><span className="text-[#80a6ff]">systems legible.</span></h1><p className="mt-9 max-w-xl text-base leading-7 text-slate-400 sm:text-lg">PorTech Systems gives complex organizations a clearer way to see dependencies, govern decisions, and direct execution when the margin for uncertainty is thin.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/products" className="group flex min-h-12 items-center gap-3 bg-[#185CFF] px-5 text-xs font-bold uppercase tracking-[0.12em] text-white transition-colors hover:bg-[#3476ff]">Explore the platform <ArrowUpRight className="h-4 w-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link><Link href="/insights" className="flex min-h-12 items-center gap-3 border border-white/15 px-5 text-xs font-bold uppercase tracking-[0.12em] text-slate-100 transition-colors hover:border-white/40 hover:bg-white/[0.04]">Read our thinking <ArrowDownRight className="h-4 w-4 text-[#7fa8ff]" /></Link></div></div><div className="flex flex-col justify-end border-l border-white/10 pt-8 lg:pl-8"><div className="border-t border-white/10 pt-5"><p className="signal-kicker">Operating principle</p><p className="mt-3 text-lg font-medium leading-7 text-slate-200">Clarity is a system property. Design for it deliberately.</p></div><div className="mt-9 grid grid-cols-2 gap-px bg-white/10">{[["01","See dependencies"],["02","Govern choices"],["03","Direct response"],["04","Preserve context"]].map(([index,label]) => <div key={index} className="bg-[#0a0f17]/90 p-4"><p className="text-[0.62rem] font-bold tracking-[0.14em] text-[#6e9aff]">{index}</p><p className="mt-5 text-xs font-semibold text-slate-300">{label}</p></div>)}</div></div></div>
    </section>
    <section className="border-b border-white/10 bg-[#0c121c] py-16 sm:py-20"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 lg:grid-cols-[92px_minmax(0,1fr)] lg:px-10"><div className="hidden lg:block"><span className="text-[0.62rem] font-bold uppercase tracking-[0.16em] text-slate-600">Platform / 01</span></div><div><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><SectionLabel index="02">A coordinated platform</SectionLabel><h2 className="mt-5 max-w-3xl text-3xl font-semibold leading-[1.02] tracking-[-0.055em] text-white sm:text-5xl">The operating layer between data and action.</h2></div><Link href="/products#compare" className="flex shrink-0 items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-[#7fa8ff] hover:text-white">Compare the platform <MoveUpRight className="h-4 w-4" /></Link></div><div className="mt-12 grid border-l border-t border-white/10 md:grid-cols-3">{products.map((product) => <Link key={product.id} href="/products" className="group border-b border-r border-white/10 p-6 transition-colors hover:bg-[#185CFF]/10"><p className="signal-kicker">{product.index} · {product.eyebrow}</p><h3 className="mt-8 text-2xl font-semibold tracking-[-0.045em] text-white">{product.name}</h3><p className="mt-4 text-sm leading-6 text-slate-400">{product.description}</p><span className="mt-8 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-slate-300 group-hover:text-[#7fa8ff]">Inspect <ArrowUpRight className="h-4 w-4" /></span></Link>)}</div></div></div></section>
    <section className="relative overflow-hidden py-20 sm:py-28"><div className="absolute inset-y-0 left-0 w-[35%] bg-[#185CFF]/[0.035]" aria-hidden="true" /><div className="relative mx-auto grid max-w-[1440px] gap-12 px-5 lg:grid-cols-[92px_minmax(0,1fr)] lg:px-10"><div className="hidden lg:block"><span className="text-[0.62rem] font-bold uppercase tracking-[0.16em] text-slate-600">Scenarios / 02</span></div><div><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><SectionLabel index="03">Operating scenarios</SectionLabel><h2 className="mt-5 max-w-3xl text-3xl font-semibold leading-[1.02] tracking-[-0.055em] text-white sm:text-5xl">Where more context changes the next move.</h2></div><p className="max-w-xs text-sm leading-6 text-slate-500">Illustrative scenarios show how PorTech patterns can clarify complex operating questions.</p></div><div className="mt-12"><CaseStudyCarousel compact /></div></div></div></section>
    <section className="border-y border-white/10 bg-[#0d1420] py-20 sm:py-28"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 lg:grid-cols-[92px_minmax(0,1fr)] lg:px-10"><div className="hidden lg:block"><span className="text-[0.62rem] font-bold uppercase tracking-[0.16em] text-slate-600">Insights / 03</span></div><div><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><SectionLabel index="04">Research and perspective</SectionLabel><h2 className="mt-5 max-w-2xl text-3xl font-semibold leading-[1.02] tracking-[-0.055em] text-white sm:text-5xl">Thinking for the systems behind the system.</h2></div><Link href="/insights" className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-[#7fa8ff] hover:text-white">All insights <ArrowUpRight className="h-4 w-4" /></Link></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{articles.slice(0,3).map((article, index) => <Link key={article.id} href="/insights" className={`group flex min-h-[275px] flex-col border p-6 transition-colors ${index === 0 ? "border-[#185CFF]/60 bg-[#185CFF]/10" : "border-white/10 bg-white/[0.02] hover:border-white/25"}`}><div className="flex justify-between"><p className="signal-kicker">{article.topic}</p><CirclePlay className="h-4 w-4 text-[#7fa8ff]" /></div><h3 className="mt-9 text-2xl font-semibold leading-[1.1] tracking-[-0.04em] text-white">{article.title}</h3><p className="mt-auto pt-6 text-xs text-slate-400">{article.author} · {article.readTime}</p></Link>)}</div></div></div></section>
    <section className="relative overflow-hidden bg-[#185CFF] py-16 sm:py-20"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.3)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.3)_1px,transparent_1px)] [background-size:48px_48px]" aria-hidden="true" /><div className="relative mx-auto flex max-w-[1440px] flex-col justify-between gap-9 px-5 lg:flex-row lg:items-end lg:px-10"><div><p className="text-[0.65rem] font-bold uppercase tracking-[0.15em] text-blue-100">Investor & press centre</p><h2 className="mt-5 max-w-3xl text-3xl font-semibold leading-[1.02] tracking-[-0.055em] text-white sm:text-5xl">A clear view of the corporate desk.</h2></div><Link href="/investors-press" className="group flex w-fit min-h-12 items-center gap-3 border border-white/45 bg-[#0b1540] px-5 text-xs font-bold uppercase tracking-[0.12em] text-white transition-colors hover:bg-[#07102f]">View releases & reports <ArrowUpRight className="h-4 w-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link></div></section>
  </div>;
}
