/** Cobalt Signal Architecture: global search is a quiet command surface with decisive, grouped results. */
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowUpRight, Search, X } from "lucide-react";
import { Link } from "wouter";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { searchIndex } from "@/data/content";

export function SearchOverlay({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) {
  const [query, setQuery] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; const isTyping = target?.tagName === "INPUT" || target?.tagName === "TEXTAREA" || target?.isContentEditable; if (event.key === "/" && !isTyping) { event.preventDefault(); onOpenChange(true); } }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [onOpenChange]);
  useEffect(() => { if (open) { const timer = window.setTimeout(() => inputRef.current?.focus(), 25); return () => window.clearTimeout(timer); } setQuery(""); }, [open]);
  const results = useMemo(() => { const normalizedQuery = query.trim().toLowerCase(); if (!normalizedQuery) return searchIndex.slice(0, 6); return searchIndex.filter((result) => `${result.title} ${result.summary}`.toLowerCase().includes(normalizedQuery)); }, [query]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[86vh] max-w-2xl overflow-hidden border border-white/10 bg-[#0c1320] p-0 text-slate-100 shadow-[0_28px_80px_rgba(0,0,0,.55)] sm:rounded-none"><DialogTitle className="sr-only">Search PorTech Systems</DialogTitle><div className="flex items-center gap-3 border-b border-white/10 px-5 py-4"><Search className="h-5 w-5 text-[#6e9aff]" /><input ref={inputRef} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products, insights, scenarios, reports" className="h-9 min-w-0 flex-1 bg-transparent text-base text-white outline-none placeholder:text-slate-500" aria-label="Search PorTech Systems" /><button onClick={() => onOpenChange(false)} className="grid h-8 w-8 place-items-center text-slate-400 hover:text-white" aria-label="Close search"><X className="h-5 w-5" /></button></div><div className="max-h-[60vh] overflow-y-auto px-2 py-3"><div className="flex items-center justify-between px-3 pb-2"><p className="signal-kicker">{query ? `${results.length} matching result${results.length === 1 ? "" : "s"}` : "Suggested routes"}</p><p className="text-[0.68rem] text-slate-600">Press Esc to close</p></div>{results.length ? <div className="grid gap-1">{results.map((result) => <Link key={`${result.type}-${result.title}`} href={result.href} onClick={() => onOpenChange(false)} className="group grid grid-cols-[86px_1fr_auto] gap-3 border border-transparent px-3 py-3 transition-colors hover:border-[#185CFF]/35 hover:bg-[#185CFF]/10"><span className="pt-0.5 text-[0.63rem] font-bold uppercase tracking-[0.13em] text-[#7fa8ff]">{result.type}</span><span><span className="block text-sm font-semibold leading-5 text-slate-100">{result.title}</span><span className="mt-1 block line-clamp-2 text-xs leading-5 text-slate-400">{result.summary}</span></span><ArrowUpRight className="mt-1 h-4 w-4 text-slate-600 transition-colors group-hover:text-[#6e9aff]" /></Link>)}</div> : <div className="m-3 border border-dashed border-white/15 px-5 py-10 text-center"><p className="text-sm font-semibold text-slate-200">No direct match yet.</p><p className="mt-2 text-sm text-slate-500">Try a product name, a topic such as resilience, or a report category.</p></div>}</div></DialogContent></Dialog>;
}
